"""empty message

Revision ID: 49f0444e48fb
Revises: 
Create Date: 2017-08-10 16:57:46.026000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f0444e48fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('testresult', sa.Boolean(), nullable=True),
    sa.Column('rspcode', sa.String(length=10), nullable=True),
    sa.Column('reqpath', sa.String(length=50), nullable=True),
    sa.Column('reqhead', sa.Text(), nullable=True),
    sa.Column('reqbody', sa.Text(), nullable=True),
    sa.Column('rsphead', sa.Text(), nullable=True),
    sa.Column('rspbody', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_result')
    # ### end Alembic commands ###
