"""empty message

Revision ID: dad854d8764a
Revises: 49f0444e48fb
Create Date: 2017-08-10 17:45:25.304000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad854d8764a'
down_revision = '49f0444e48fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_result', sa.Column('mockid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_result', 'mockid')
    # ### end Alembic commands ###
